_wandb:
    value:
        cli_version: 0.19.9
        m: []
        python_version: 3.11.9
        t:
            "1":
                - 1
                - 41
                - 55
            "2":
                - 1
                - 41
                - 55
            "3":
                - 1
                - 2
                - 3
                - 13
                - 23
                - 55
                - 62
            "4": 3.11.9
            "5": 0.19.9
            "8":
                - 1
                - 5
            "12": 0.19.9
            "13": linux-x86_64
batch_size:
    value: 128
deterministic:
    value: false
learning_rate:
    value: 0.001
model:
    value: resnet18
num_epochs:
    value: 100
optimizer:
    value: Adam
seed:
    value: 2025
